# Made by XiaoJibaZhanshi
# You can add more levels, but not upgrades!

# The way the NPC is going to work is that it'll stand still and "collect" the crop you've farmed
# At the end of the npc-lifetime-seconds you'll be able to click the NPC and get the rewards
# If you leave him hanging or leave the server during that time, you lose those rewards (he despawns after 5 min)

upgrades:
  notification-on-trigger: true # set to false if the upgrades are meant to be triggered a ton
  player-speed:
    levels:
      1:
        chance-to-trigger: 1.0 # this is in percent
        cost: 0 # has to be a full integer
        potion-amplifier: 0 # lowest potion amplifier, this has to be a full integer (no decimals)
      2:
        chance-to-trigger: 2.0
        cost: 200
        potion-amplifier: 0
      3:
        chance-to-trigger: 4.0
        cost: 500
        potion-amplifier: 0
  looting:
    levels:
      1:
        chance-to-trigger: 1.0
        cost: 0
        crop-multiplier: 2 # if left on 2 - will give 2 crops instead of 1 when farming
  auto-replant:
    levels:
      1:
        chance-to-trigger: 1.0
        cost: 0
  meteor:
    levels:
      1:
        chance-to-trigger: 1.0
        cost: 0
        radius: 3
  npc:
    levels:
      1:
        chance-to-trigger: 0.1
        cost: 0
        npc-lifetime-seconds: 30 # the npc retrieves 1 of whatever crop you farmed per second by the way

guis:
  fill:
    enabled: true
    material: gray_stained_glass_pane
  main-gui:
    name: "&7Upgrades"
    rows: 3 # Upgrades will be centered no matter how many rows you have
  upgrade-guis:
    rows: 3 # Levels are NOT centered in the GUI
    hide-far-levels: true # this will simply make it so that if a level is 2 higher than the player's,
    # it will make it into a barrier block named "Unlock previous level first"
